spring:
  application:
    name: sazzler-product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/sazzler_order_db
    username: amodhyh
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    topic:
      name: sazzler-product-topic

#    the kafka broker address
    bootstrap-servers: localhost:9092
#    the broker adress and serializer and deserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: sazzler-product-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

# Actuator configuration for monitoring

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
        defaultZone: http://amodhyh:1234@localhost:8761/eureka/

server:
    port: 8083